select * from DS_TOUR where GIA BETWEEN 50 AND 10000

CREATE NONCLUSTERED INDEX [_dta_index_DS_TOUR_13_885578193__K3_1_2] ON [dbo].[DS_TOUR]
(
	[GIA] ASC
)
INCLUDE([MA_TOUR],[TEN_TOUR]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


