

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_CHUYENDI_KH_13_1806629479__K4_K3] ON [dbo].[CHUYENDI_KH]
(
	[TRANGTHAI] ASC,
	[MA_TOUR] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_DS_TOUR_13_885578193__K1_3] ON [dbo].[DS_TOUR]
(
	[MA_TOUR] ASC
)
INCLUDE([GIA]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

SELECT CD.MA_TOUR, DS.GIA,  COUNT(*) as sl, DS.GIA*count(*) AS TONGTIEN
FROM DS_TOUR DS, CHUYENDI_KH CD
WHERE DS.MA_TOUR = CD.MA_TOUR and CD.TRANGTHAI = N'ĐÃ XÁC THỰC'
GROUP BY CD.MA_TOUR, DS.GIA