CREATE OR ALTER TRIGGER TRIGGER_UPDATE_MANV ON NHANVIEN FOR UPDATE
AS
BEGIN
	IF (@@ROWCOUNT=0)
		BEGIN
			PRINT N'BẢNG NHANVIEN KHÔNG CÓ DỮ LIỆU'
			return
		END
	UPDATE T1 SET T1.MANV = T3.MANV
	FROM HIEUSUAT_NV T1, DELETED T2, INSERTED T3
	WHERE T1.MANV = T2.MANV

	UPDATE T1 SET T1.MANV = T3.MANV
	FROM PHANCONG T1, DELETED T2, INSERTED T3
	WHERE T1.MANV = T2.MANV
END
go

CREATE OR ALTER TRIGGER PHANCONG_CHUYENDI 
ON PHANCONG AFTER INSERT
AS
BEGIN
	DECLARE @MANV NVARCHAR(10);
	DECLARE @MATOUR NVARCHAR(10);
	SELECT @MANV = PHANCONGLIST.MANV FROM INSERTED PHANCONGLIST;
	SELECT @MATOUR = PHANCONGLIST.MA_TOUR FROM INSERTED PHANCONGLIST;

	UPDATE CHUYENDI_KH 
	SET CHUYENDI_KH.MANV = @MANV
	WHERE CHUYENDI_KH.MA_TOUR = @MATOUR

END
go

create or alter trigger trigger_hd_nv ON NHANVIEN
	AFTER INSERT
AS
BEGIN
	DECLARE @MANV NVARCHAR(10);
	DECLARE @DATE_CURRENT DATETIME = CURRENT_TIMESTAMP;
	SELECT @MANV = NHANVIENLIST.MANV FROM INSERTED NHANVIENLIST;
								
	INSERT INTO hopdong(MANV,NBD) VALUES (@MANV, @DATE_CURRENT);

END
GO