SELECT DISTINCT KH.MAKH, KH.HOTEN, DS.MA_TOUR, DS.TEN_TOUR, CD.TRANGTHAI
FROM KHACHHANG KH, CHUYENDI_KH CD, DS_TOUR DS
WHERE (KH.PHAI = 'NAM') 
AND (DS.MA_TOUR = CD.MA_TOUR)
AND (CD.MAKH = KH.MAKH AND CD.TRANGTHAI = N'ĐANG CHỜ XÁC THỰC')

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_CHUYENDI_KH_13_1806629479__K4_K2_K3] ON [dbo].[CHUYENDI_KH]
(
	[TRANGTHAI] ASC,
	[MAKH] ASC,
	[MA_TOUR] ASC
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
CREATE STATISTICS [_dta_stat_1806629479_2_3] ON [dbo].[CHUYENDI_KH]([MAKH], [MA_TOUR])
CREATE STATISTICS [_dta_stat_1806629479_4_3_2] ON [dbo].[CHUYENDI_KH]([TRANGTHAI], [MA_TOUR], [MAKH])
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [_dta_index_KHACHHANG_13_1925581898__K3_K1_2] ON [dbo].[KHACHHANG]
(
	[PHAI] ASC,
	[MAKH] ASC
)
INCLUDE([HOTEN]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
